---
openapi: 3.0.0
info:
  title: IllnessLib Progect
  description: ""
  version: 1.0.1
servers:
- url: https://virtserver.swaggerhub.com/ROMANMANACHYNSKYI/IllnessLib/1.0.1
  description: SwaggerHub API Auto Mocking
paths:
  /Doctor/InitialInformation:
    get:
      responses:
        "200":
          description: List of Appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
components:
  schemas:
    DoctorInitialInformation_Initials:
      type: object
      properties:
        FirstName:
          maxLength: 100
          minLength: 2
          type: string
        MidleName:
          maxLength: 100
          minLength: 2
          type: string
        LastName:
          maxLength: 100
          minLength: 2
          type: string
      example: null
    DoctorInitialInformation_Data:
      type: object
      properties:
        Day:
          maximum: 31
          minimum: 1
          type: number
        Month:
          maxLength: 9
          minLength: 3
          type: string
        Year:
          maxLength: 4
          minLength: 4
          type: number
      example: null
    inline_response_200:
      type: object
      properties:
        Initials:
          $ref: '#/components/schemas/DoctorInitialInformation_Initials'
        Time:
          type: number
        Data:
          $ref: '#/components/schemas/DoctorInitialInformation_Data'
        Symptomes:
          type: array
          items:
            type: string
        PatientID:
          type: number
