---
openapi: 3.0.0
info:
  title: IllnessLib Progect
  description: ""
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ROMANMANACHYNSKYI/IllnessLib/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
